name: widgetbook_caveo
description: "Widgetbook for visualizing the Dori Design System components"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0
  dori:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  widgetbook_generator: ^3.10.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
