name: widgetbook_caveo
description: "Widgetbook for visualizing the Dori Design System components"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  widgetbook: 3.20.2
  widgetbook_annotation: 3.9.0
  dori:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.10.5
  widgetbook_generator: 3.20.1
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
